### ISSUE TITLE
Error when using DllImport

### ISSUE THREAD

**Issue by olluz** [3F/DllExport#110]
I have an exported method:
`[DllExport("Start", CallingConvention = CallingConvention.Cdecl)]`
`public static bool Start(IntPtr hwndMain)`
`{`
`    return true;`
`}`

The exe will find this without problems, but as soon as I add any DllImport I get this error message:
"The procedure entry point Start could not be located in the dynamic link library."

Is that expected ?

**Comment by 3F** [comment]
@olluz Can you illustrate something what are you trying to do? Unmanaged side is also important. 

I think, for you case (due to #105) you need to use stackoverflow service instead.

Btw, 
4. Please try to use [basic formatting for your code examples](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by 3F** [comment]
closed due inactivity
