### ISSUE TITLE
Other NuGet packages are not visible as installed when DLLExport enabled for project

### ISSUE THREAD

**Issue by engycz** [3F/DllExport#152]
Steps to reproduce:
* Create new Console application (.NET Framework)
* Add NuGet package PInvoke.Windows.Core
* Add NuGet package DllExport (don't enable it for the project)
* Both packages are visible as installed
![obrazek](https://user-images.githubusercontent.com/6651271/82021376-ffd4a280-968a-11ea-8afc-6daeaf9d1724.png)
![obrazek](https://user-images.githubusercontent.com/6651271/82021603-678aed80-968b-11ea-9949-6038ddae52d1.png)
* Close Visual Studio
* Run DllExport.bat, check Installed and push Apply
* Open the solution in Visual Studio
* Only DllExport package is reported as installed
![obrazek](https://user-images.githubusercontent.com/6651271/82021304-e895b500-968a-11ea-91cc-1f953638f830.png)
![obrazek](https://user-images.githubusercontent.com/6651271/82021656-81c4cb80-968b-11ea-9d43-9235cf724aef.png)
* PInvoke.Windows.Core is working but it's not updated/restored as VS don't know about it

. . .

* `DllExport -version`: 1.7.1
* Used Visual Studio / MSBuild / ...: Visual Studio Community 2019 16.5.5

Demo Project files / Samples / etc.:
Packed solution before DllExport enabled for the project [Test.zip](https://github.com/3F/DllExport/files/4632717/Test.zip)

**Comment by 3F** [comment]
Thanks for the detailed report

Also confirmed for previous release **1.7.0.**

This is because of NuGet logic that uses a single [NuGetProject](https://github.com/NuGet/NuGet.Client/blob/f5916a527c442f896f787c593252b37a345da835/src/NuGet.Core/NuGet.PackageManagement/Projects/NuGetProject.cs) implementation even for multiple [providers](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/INuGetProjectProvider.cs) as I can see here:

https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/NuGetProjectFactory.cs#L84-L91

And because of order as follow:

`... -> NetCorePackageReferenceProjectProvider -> LegacyPackageReferenceProjectProvider -> MSBuildNuGetProjectProvider -> ...`

I'll try to review this month.

**Temporary solution:** Either upgrade *packages.config* to *PackageReference* or remove any *PackageReference* records from affected project files (.csproj, ...) after apply button if you want to list other packages in VS IDE.

**Comment by 3F** [comment]
Done. You can test it via CI build. Planned for 1.7.3
