### ISSUE TITLE
How to implement DLL_PROCESS_ATTACH in DLLMain

### ISSUE THREAD

**Issue by Ptkatz** [3F/DllExport#221]
I want to attach DLL execute function in unmanaged program

**Comment by 3F** [comment]
Hello,

The user actions for DllMain (including the reason when process is 
attaching) are not yet implemented because actually it's not the basic 
export as I explained it briefly in the past, #5

It requires some wrapping of the _CorDllMain after completely 
initialized CLR VM;
either through modified PE writter as part of my modified assembler 
(coreclr repo in my profile) or through something similar, I think.

However, personally I don't have yet the opportunity to continue 
anything for a while as explained here #219
Maybe later, maybe not; I don't know either. Sorry, and Thanks for your 
interest!

**Comment by Ptkatz** [comment]
OK, thank you!
