### ISSUE TITLE
Failed to write to log file ... because it is being used by another process

### ISSUE THREAD

**Issue by KieranRosinger** [3F/DllExport#223]
I'm having an issue with building a project using DLLExport when using a Directory.Build.rsp file to set the msbuild /fl1 flag.

The error that occurs is
```
"C:\DLLExportIssue\Test\Test.sln" (default target) (1) ->
"C:\DLLExportIssue\Test\Test.csproj" (default target) (2) ->
(DllExportRestorePkg target) ->
  MSBUILD : Logger error MSB4104: Failed to write to log file "msbuild1.log". The process cannot access
 the file 'C:\DLLExportIssue\Test\msbuild1.log' because it is being used by another process. [C:\DLLExp
ortIssue\Test\Test.csproj]
  C:\DLLExportIssue\Test\Test.csproj(34,5): error MSB3073: The command ".\DllExport.bat  -action Restor
e" exited with code -1.
```

[DLLExportIssue.zip](https://github.com/3F/DllExport/files/11332679/DLLExportIssue.zip)

I have attached the solution and steps to reproduce. This is a new Hello World Console App .Net6.0 from Visual Studio 2022 with DLLExport installed onto the project.

The issue is only seen when a Directory.Build.rsp file is present in the solution folder that sets msbuild flag /fl1. 

Please can you advise if there is a work around or how I can resolve the issue?

**Comment by 3F** [comment]
Hello,

Thanks for the prepared project example to reproduce. This is appreciated!

Conflict between processes due to several sources (+exec task in csproj) 
for a single destination is possible for filelogger.
In order to avoid problem try to split dst or use other logger or 
redirect std stream
OR call DllExport.bat separately before msbuild

For example,

DllExport -action Restore

Then,

msbuild -t:Restore -t:Build

**Comment by 3F** [comment]
Future versions will no longer be affected by .rsp, since 3db370a
For the current 1.7.4 please continue to use `DllExport -action Restore & msbuild ...` as before.

Let me know if the problem is not solved.
