### ISSUE TITLE
Source: Configurator/ConfVersion.cs is not checked in currently

### ISSUE THREAD

**Issue by HeikoStudt** [3F/DllExport#31]
Hi,

in the source code:
The file Configurator/ConfVersion.cs is missing and was probably not checked in..
For the moment the master does not compile.

MFG

**Comment by 3F** [comment]
looks normal: https://ci.appveyor.com/project/3Fs/dllexport/branch/master

Read:

* **[How to Build](https://github.com/3F/DllExport#how-to-build)**
* **[How to Debug](https://github.com/3F/DllExport#how-to-debug)**

Configurator/ConfVersion.cs will be generated via vssbe scripts. Current actived Events/Actions:

```
 3 / 3] Pre-Build      :: [!][!][!]
 3 / 3] Post-Build     :: [!][!][!]
 0 / 0] Cancel-Build   :: 
 0 / 0] CommandEvent   :: 
 0 / 0] Warnings-Build :: 
 0 / 0] Errors-Build   :: 
 0 / 0] Output-Build   :: 
 1 / 1] Sln-Opened     :: [!]
 0 / 0] Sln-Closed     :: 
 0 / 0] Transmitter    :: 
 0 / 0] Logging        :: 
```

```
...
action 'define dynamic constants'
action 'Prepare output directory'
action 'Update version number'
action 'Update ConfVersion'      <<<<<<<<<<<<<<<<<<
action 'Binaries & tools ...'
action 'Provide our ILAsm & ILDasm'
action 'Packing with GetNuTool ...'
...
```


If you just want to get binaries, use:

```batch
> build
```
*No any plugins required because of CIM version.*

For support this via VisualStudio IDE you should have installed plugin.

For **[coreclr](https://github.com/3F/DllExport#coreclr---ilasm--ildasm)**:  Make sure that you have installed CMake, then `build_s all x86 x64 Release` etc.

**Comment by HeikoStudt** [comment]
Thanks for the fast answer.
I didn't see that the build.bat was required as a first step. It would be nice to change the filename to be "ConfVersionGenerated.cs" or such, so that one has some clue.
After I have started build.bat once, I can compile the Configurator.

MFG

**Comment by 3F** [comment]
@HeikoStudt 

> I didn't see that the build.bat was required as a first step

it's not a first step :) this for build via console (including CI etc.)

**for Visual Studio**, see [this](https://marketplace.visualstudio.com/items?itemName=DenisKuzminreg.vsSolutionBuildEvent-11615)

> "ConfVersionGenerated.cs"

I'm not sure that's will be more clear, so probably to change this with [another logic](http://vssbe.r-eg.net/doc/Examples/Version/) is better. For example like I did it for [Conari](https://github.com/3F/Conari) project:

* https://github.com/3F/Conari/blob/master/Conari/ConariVersion.cs is already generated and part of this repo.
* **But**, information below will be updated only when "PublicRelease" cfg is selected for build:

```csharp
public const string S_REV = "39634";
...
public const string BRANCH_SHA1 = "aa4e6b1";
public const string BRANCH_NAME = "master";
public const string BRANCH_REVC = "45";
...
```
this way helps to avoid changing for SCM from common user-builds

Well, I'll look this later

**Comment by 3F** [comment]
now it's part of this repo: SHA1 & rev will be updated only when PublicRelease cfg is used
