### ISSUE TITLE
.Net Standard Support

### ISSUE THREAD

**Issue by longlostbro** [3F/DllExport#67]
Are there any plans or thoughts on the possibility of targeting .Net Standard instead of .Net Framework?

**Comment by 3F** [comment]
@longlostbro 

> any plans or thoughts on the possibility of targeting 

Do you mean the just usage of this tool with .net framework through .net std because of this target (i.e. only where it will be ~available) ? 

In general, we still have no support of .net core: https://github.com/3F/DllExport/issues/63. Still not yet:  https://github.com/3F/DllExport/issues/17#issuecomment-335001440

**Comment by 3F** [comment]
Implemented in 1.7. And stable as of Release Candidate state. Thanks to all for testing and feedback!

Final release scheduled for this week. Follow the news.

**Comment by marcussacana** [comment]
Thank you so much for your hard work in a open source freeware <3

**Comment by 3F** [comment]
> Thank you so much for your hard work in a open source freeware <3

I am glad to hear that this is still useful! And I can still continue develop something like this and more for open source!

I also remind everyone, you can support me and my free work in open source as you prefer.

* About and details: http://3F.github.com/Donation/

Recently I also started ko-fi&patreon with backlog-like posts: https://ko-fi.com/github3f
And started twitter for news and related: https://twitter.com/GitHub3F
.
Enjoy
.
.
Yours, [github.com/3F](https://github.com/3F)
