### ISSUE TITLE
Is it possible to have a multi-architecture file?

### ISSUE THREAD

**Issue by Genteure** [3F/DllExport#81]
e.g. managed AnyCPU with 32bit unmanaged, for maximum compatibility.

Obviously there's no such feature now, I'd like to know if it's even possible at all.

Use case: I'm writing a plugin for a managed AnyCPU program. Some user love to ignore usage tutorial and double click dll files trying to install. Normal Windows system will ask "You are trying to open a system file", but some random modified Windows will default open dll using `Regsvr32`.
I would like to export a `DllRegisterServer` to pop a MessageBox, while able to run on both 32bit and 64bit system.

**Comment by 3F** [comment]
> Is it possible to have a multi-architecture file?

Native pe module cannot work with different architectures. This impossible even because of different headers, like the optional header structure:

* https://docs.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-_image_optional_header
* https://docs.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-_image_optional_header64

```cpp
typedef struct _IMAGE_NT_HEADERS64 {
  DWORD                   Signature;
  IMAGE_FILE_HEADER       FileHeader;
  IMAGE_OPTIONAL_HEADER64 OptionalHeader;
} IMAGE_NT_HEADERS64, *PIMAGE_NT_HEADERS64;
```

* https://github.com/3F/Conari/blob/master/Conari/PE/Hole/ExportDirectory.cs#L197
```csharp
            // move to NumberOfRvaAndSizes

            if(ifh.SizeOfOptionalHeader == 0xE0) { // IMAGE_OPTIONAL_HEADER32
                stream.Seek(0x5C, SeekOrigin.Current);
            }
            else if(ifh.SizeOfOptionalHeader == 0xF0) { // IMAGE_OPTIONAL_HEADER64
                stream.Seek(0x6C, SeekOrigin.Current); // <<< +0x10
```

Thus, finally you should provide either pe32 or pe32+ module (aka pe64).

But, you can just provide both pe32 and pe32+ modules and just execute the one of this for related architecture.

The most easy way, you can use some installation wizard. Or just combine modules via other your 32bit application that will just select 32/64 architecture.

Our DllExport may provide both 32 & 64 pe-modules (dll or exe) in relevant folders:

* `-action Configure` then select both arch (x86 + x64)
* Now you can provide both architectures from output folder `\x32\Library.dll` and `\x64\Library.dll`

## The most complex way

Actually, pe module may contain anything including code for several architectures, but we need also wrap the entry point to inject our specific tool that will understand this (for example, extract and execute code only for related architecture 32/64). Something like UPX.

But, as I was saying before, our modified .net modules **are not really true native modules.** They initially contains injected a common entry point by default for communicate with _CorExeMain / _CorDllMain -> mscoree.dll. Because it still contains opcodes only for CLR (of course except native wrapping and so on).

However, I will also be happy to hear other possible ways if I missed something :)

**Comment by Genteure** [comment]
This is what got me thinking that it may be possible.

![image](https://user-images.githubusercontent.com/11240579/44687057-bd1c0280-aa82-11e8-8a1c-feac62a89681.png)
![image](https://user-images.githubusercontent.com/11240579/44686893-349d6200-aa82-11e8-97c1-ed88f2df22a4.png)
![image](https://user-images.githubusercontent.com/11240579/44687147-0409f800-aa83-11e8-9ac9-042dcf0f03ca.png)

I know basic nothing about file struct before asking. After checking [dnSpy's code](https://github.com/0xd4d/dnSpy/blob/039405f69e60aa850e3770ea6cc94f84dde61dcf/dnSpy/dnSpy.Decompiler/MSBuild/ProjectWriter.cs#L294-L324), I understand the difference between AnyCPU and x86, and if a file contain not only managed IL code then it's x86 only. Tried to play with `Is32BitRequired` `Is32BitPreferred` `IsILOnly`, but apparently Microsoft did a great job checking if a executable file is valid. If any of that three is changed to a "incorrect" value, .NET will throw a `BadImageFormatException` when calling `Assambly.LoadFrom`.

Well, it's not possible I guess.

**Comment by 3F** [comment]
> If any of that three is changed to a "incorrect" value, .NET will throw a BadImageFormatException when calling Assambly.LoadFrom.

It's a little bit other story. I mean, it will be still under CLR and its domains. While LoadLibrary (from Kernel32) will just try to understand this through specific header.

Independent arch (AnyCPU) is possible because of wrapping as I mentioned above. 
That is, for my understanding or view, in general, this *multi-architecture* is possible thing by wrapping over CLR wrapping :) i.e. custom injection for entry point (see my note for DllMain issue). 

But truth is that .., this is really giant overhead for an insignificant convenience (moreover, some things will add other new inconvenience for this ~convenience). Therefore, the easiest or more stable way is to provide both.
