### ISSUE TITLE
the C++ part

### ISSUE THREAD

**Issue by haller9816** [3F/DllExport#83]
* Environment ( VS, MSBuild, ...): Visual Studio 2017

Hi Denis, hi all,

it's me again. I have the VB.NET code with DLLEXPORT with no ERROR.
![dllexport_visualbasic](https://user-images.githubusercontent.com/42702955/44817735-a0004480-abe6-11e8-89c6-ab8d22cde5c6.JPG)

Now I try the C++ calling as a console application (later it should be a dll) and have problems:
![dllexport_cpp_part](https://user-images.githubusercontent.com/42702955/44817844-04230880-abe7-11e8-85aa-a1e65823d117.JPG)
errors are: GetProcAddress, HMODULE, lib and LoadLibrary are not found or declared (looks if I have something to load)
and I think the declaration:
extern "C" _declspec(dllexport) double cNetz(double p);
is not complete.
I have no experience with C or C++, I do programm in FORTRAN. That was enough for technical calculations.
Would you help me again?

Olaf

**Comment by 3F** [comment]
Looks like we need to add more info for beginners, but how does it related ... hmmm -_-

Also, as I understood, my two latest screencasts that combines a several methods at once (for both host sides) completely confuses some people. Some people think that this is only about exporting from .NET (this dllexport), others combines unnecessary code, and so on. Well, detailed chapters with description seems does not help.

Olaf, your 6 line code in details:

* You don't need underscore character for **lpProcName** arg if you have no this proc:
 
```cpp
GetProcAddress(
    _In_ HMODULE hModule,
    _In_ LPCSTR lpProcName   // <<< You have "Netz" exported function, thus you need this and not "_Netz"
    );
```

* By the way, **__declspec** with double underscore "__" is a C++ standard and it's more recommended, at least outside of MSVC compiler. Same for other keywords like for calling conventions: __cdecl, __stdcall, ... but **except** for data types like __int32, __int64, ... (MS features).
    * You can also avoid __cdecl in `double(__cdecl *Netz)` if your projects uses this convention by default. That is: `double(*Netz)(double p)`

* **But** for your case, **you do not need** this part at all:

```cpp
extern "C" __declspec(dllexport) double cNetz(double p)
```

This was for .NET to use unmanaged library, if you remember, like:

```csharp
using(var l = new ConariL("unmanaged_c_library.dll"))
{
    Double val = l.DLR.cNetz<Double>(1234); // __declspec(dllexport) double cNetz(double p)
```

* Please be careful, managed and unmanaged types are not identical, and also their sizes may not be equal! 
  Moreover in C and C++ lot of things can be redefined even for std types like #define double __int64. So, You should always look for equivalent for bytes. Check this via sizeof: **sizeof(double)**
 Default types here: https://docs.microsoft.com/en-us/cpp/cpp/data-type-ranges

* LoadLibrary() & GetProcAddress() are parts of Win API, you need **windows.h**. Add the following headers into your **stdafx.h** (because you're using precompiled headers as I can see):


```cpp
// Win API including +LoadLibrary/Ex and lot of other related things
#include <windows.h>

// if you want to work with TCHAR like from my screencasts:
// otherwise you can via wchar_t or char, etc.
#include <tchar.h>
```

* Try do not use **typedef** inside any functions or methods. From screencasts it was for quick illustration of the main steps. Header files are better place.

**Comment by haller9816** [comment]
Hi Denis, hi all,

since your comment I changed something: 
I delete the underscors
I added 
#include <Windows.h> in stdafx.h and 
delete "extern "C" __declspec(dllexport) double cNetz(double p)"

That gives a compiling without errors 

but if I run the program I get an exception error when the function is called. 
![dllexport_cpp_part_02](https://user-images.githubusercontent.com/42702955/44875906-c3d39100-ac9f-11e8-8928-09b85cf6bb29.JPG)

May be the parameter list is not ok. (I attached a Dependency Walker printout from the vb.net dll. Shoudn't be there "Netz@8"?
![dep walk_vb_dll](https://user-images.githubusercontent.com/42702955/44876517-a30c3b00-aca1-11e8-89c8-4821fb319080.JPG)

I don't know what to do. And I must confess I didn't understand all of the comment. May be I consider not all.
Please..... again. 

Olaf

**Comment by 3F** [comment]
Remove `#define double __int64` This note was about **possible** different sizes! For your future work with data, because it can be fatal for some calculation isn't it? So you don't need this line too.

> Shoudn't be there "Netz@8"

There is some difference from msvc compiler, but even for msvc if 64bit environment, no, and for 32bit env with __cdecl also no. Here I meant C compiler or C++ with C-mangling. 

Some other compilers does this also differently: MSVC, GCC, CLang, ...

> Olaf - the C++ beginner :-)

Why you don't what to use Fortran if you already know this perfectly?!

About **Unhandled exception (KernelBase.dll):**

More like the export works well, and you just have problems in your VB function :) Check this out.

Try to debug in mixed code. Probably will help to isolate problem.

**Comment by haller9816** [comment]
Hi Denis,
I would do it in Fortran, but I don't know how. But I will try.
And about the problems in the VB function, I will use the mixed code debugging.

Thank you for your help.

Olaf

**Comment by 3F** [comment]
Try to set [mixed] debugging type in properties for C++ project. For how 
does it work see in screencast part-2 when stepping into managed code 
from unmanaged. Then try again to debug at runtime.
