### ISSUE TITLE
Is there any limitations?

### ISSUE THREAD

**Issue by CaledoniaProject** [3F/DllExport#89]
I came from [this post](https://movaxbx.ru/2018/10/23/injecting-net-assemblies-into-unmanaged-processes/), it uses a much more complex way to load .NET DLL into unmanaged processes.

```
int wmain(int argc, wchar_t* argv[])
{
    HRESULT hr;
    ICLRMetaHost *pMetaHost = NULL;
    ICLRRuntimeInfo *pRuntimeInfo = NULL;
    ICLRRuntimeHost *pClrRuntimeHost = NULL;
    
    // build runtime
    hr = CLRCreateInstance(CLSID_CLRMetaHost, IID_PPV_ARGS(&pMetaHost));
    hr = pMetaHost->GetRuntime(L"v4.0.30319", IID_PPV_ARGS(&pRuntimeInfo));
    hr = pRuntimeInfo->GetInterface(CLSID_CLRRuntimeHost, 
        IID_PPV_ARGS(&pClrRuntimeHost));
    
    // start runtime
    hr = pClrRuntimeHost->Start();
    
    // execute managed assembly
    DWORD pReturnValue;
    hr = pClrRuntimeHost->ExecuteInDefaultAppDomain(
    	L"T:\\FrameworkInjection\\_build\\debug\\anycpu\\InjectExample.exe", 
    	L"InjectExample.Program", 
    	L"EntryPoint", 
    	L"hello .net runtime", 
    	&pReturnValue);
    
    // free resources
    pMetaHost->Release();
    pRuntimeInfo->Release();
    pClrRuntimeHost->Release();
    
    return 0;
}
```

Then I started wondering, since DLLExport is so much easier to use, does it have any limitations? The [Wiki](https://github.com/3F/DllExport/wiki) says nothing about it.

**Comment by 3F** [comment]
> since DLLExport is so much easier to use, does it have any limitations? The Wiki says nothing about it.

Isn't it? wiki:

* [About data types](https://github.com/3F/DllExport/wiki/Quick-start#about-data-types)
* [About project types](https://github.com/3F/DllExport/wiki/Quick-start#about-project-types)

...

But:

> does it have any limitations

In general, you need to clarify the question because of really abstract case.

The mentioned way is the old known way through **Unmanaged API**. But this is other big story.

Here's MSDN full docs about runtime hosts, compilers, disassemblers, etc.: 

* https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/index
